"""Deterministic, non-LLM rendering of an `ApiIntelligenceResult` into every
output format the agent's spec asks for: cURL, OpenAPI YAML, a Postman
collection, a Markdown summary, and a self-contained HTML dashboard.

Nothing here calls the LLM again — every renderer is a pure function of the
already-produced `ApiIntelligenceResult`, so re-exporting a completed run in
a different format (the export endpoints in
`app.api.v1.routers.api_intelligence`) never re-runs analysis, costs
nothing, and is fully deterministic. This is also what "reuse output
rendering, don't duplicate infrastructure" means in practice for this
agent: one result object, N cheap projections of it.
"""

from __future__ import annotations

import html
import json
from urllib.parse import urlparse

import yaml

from app.agents.api_intelligence.schemas import (
    ApiEndpoint,
    ApiIntelligenceResult,
    FindingSeverity,
    SecurityFinding,
)

# ---------------------------------------------------------------------------
# cURL
# ---------------------------------------------------------------------------


def curl_for_endpoint(endpoint: ApiEndpoint) -> str:
    """A runnable-shaped (not necessarily executable — placeholder auth)
    cURL command for one documented endpoint."""
    url = f"{endpoint.base_url.rstrip('/')}{endpoint.path}" if endpoint.base_url else endpoint.path
    parts = [f"curl -X {endpoint.method}", f'"{url}"']
    if endpoint.authentication_required:
        parts.append('-H "Authorization: Bearer <token>"')
    parts.append('-H "Content-Type: application/json"')
    if endpoint.method in ("POST", "PUT", "PATCH") and endpoint.request_example:
        body = endpoint.request_example.replace("'", "'\\''")
        parts.append(f"-d '{body}'")
    return " \\\n  ".join(parts)


# ---------------------------------------------------------------------------
# OpenAPI YAML
# ---------------------------------------------------------------------------


def render_openapi_yaml(result: ApiIntelligenceResult) -> str:
    """Best-effort OpenAPI 3.0 document. "Best-effort" because Markdown
    prose doesn't reliably carry a machine JSON Schema for request/response
    bodies — those are attached as free-text `description` (with the
    original example under `x-example`) rather than fabricated as a typed
    schema the documentation never actually specified."""
    paths: dict[str, dict[str, object]] = {}
    for endpoint in result.endpoints:
        path_item = paths.setdefault(endpoint.path, {})
        operation: dict[str, object] = {
            "summary": endpoint.description or f"{endpoint.method} {endpoint.path}",
            "parameters": [
                {
                    "name": p.name,
                    "in": p.location if p.location != "body" else "query",
                    "required": p.required,
                    "description": p.description,
                    "schema": {"type": p.type or "string"},
                }
                for p in endpoint.parameters
                if p.location != "body"
            ],
            "responses": {
                code: {"description": f"HTTP {code}"} for code in (endpoint.status_codes or ["200"])
            },
        }
        if endpoint.version:
            operation["x-version"] = endpoint.version
        if endpoint.owner:
            operation["x-owner"] = endpoint.owner
        if endpoint.request_example:
            operation["requestBody"] = {
                "description": "See x-example-request for the documented sample payload.",
                "content": {"application/json": {"x-example-request": endpoint.request_example}},
            }
        if endpoint.response_example:
            operation["responses"].setdefault("200", {})["x-example-response"] = (  # type: ignore[index]
                endpoint.response_example
            )
        if endpoint.authentication_required:
            operation["security"] = [{"bearerAuth": []}]
        path_item[endpoint.method.lower()] = operation

    document: dict[str, object] = {
        "openapi": "3.0.3",
        "info": {
            "title": f"{result.repository_full_name} API",
            "description": result.executive_summary
            or "Generated by the API Intelligence Agent from Markdown documentation.",
            "version": (
                result.endpoints[0].version
                if result.endpoints and result.endpoints[0].version
                else "1.0.0"
            ),
        },
        "servers": [{"url": url} for url in result.base_urls]
        or [{"url": "https://api.example.com"}],
        "paths": paths,
    }
    if any(e.authentication_required for e in result.endpoints):
        document["components"] = {
            "securitySchemes": {"bearerAuth": {"type": "http", "scheme": "bearer"}}
        }

    return yaml.safe_dump(document, sort_keys=False, default_flow_style=False)


# ---------------------------------------------------------------------------
# Postman collection (v2.1.0)
# ---------------------------------------------------------------------------


def render_postman_collection(result: ApiIntelligenceResult) -> dict[str, object]:
    items = []
    for endpoint in result.endpoints:
        raw_url = (
            f"{endpoint.base_url.rstrip('/')}{endpoint.path}"
            if endpoint.base_url
            else endpoint.path
        )
        parsed = urlparse(raw_url)
        headers = [{"key": "Content-Type", "value": "application/json"}]
        if endpoint.authentication_required:
            headers.append({"key": "Authorization", "value": "Bearer {{token}}"})

        request: dict[str, object] = {
            "method": endpoint.method,
            "header": headers,
            "url": {
                "raw": raw_url,
                "host": [parsed.netloc] if parsed.netloc else [raw_url],
                "path": [p for p in parsed.path.split("/") if p] or [endpoint.path],
            },
            "description": endpoint.description,
        }
        if endpoint.method in ("POST", "PUT", "PATCH") and endpoint.request_example:
            request["body"] = {"mode": "raw", "raw": endpoint.request_example}

        items.append(
            {
                "name": f"{endpoint.method} {endpoint.path}",
                "request": request,
                "response": (
                    [
                        {
                            "name": "Example response",
                            "originalRequest": request,
                            "body": endpoint.response_example,
                        }
                    ]
                    if endpoint.response_example
                    else []
                ),
            }
        )

    return {
        "info": {
            "name": f"{result.repository_full_name} API",
            "description": result.executive_summary,
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "item": items,
    }


# ---------------------------------------------------------------------------
# Markdown summary
# ---------------------------------------------------------------------------


def render_markdown_summary(result: ApiIntelligenceResult) -> str:
    lines: list[str] = [f"# API Intelligence Report — {result.repository_full_name}", ""]
    if result.executive_summary:
        lines += [result.executive_summary, ""]

    lines += ["## Scores", ""]
    s = result.scores
    lines += [
        f"- **Overall Readiness:** {s.overall_readiness_score}/100",
        f"- Documentation Completeness: {s.documentation_completeness}/100",
        f"- Security: {s.security_score}/100",
        f"- API Quality: {s.api_quality_score}/100",
        f"- Readability: {s.readability_score}/100",
        f"- Consistency: {s.consistency_score}/100",
        "",
    ]

    lines += ["## Endpoints", ""]
    if not result.endpoints:
        lines += ["_No endpoints were extracted from the provided documentation._", ""]
    for e in result.endpoints:
        lines += [
            f"### {e.method} {e.path}",
            "",
            e.description or "_No description documented._",
            "",
            f"- Auth required: {'yes' if e.authentication_required else 'no'}",
            f"- Owner: {e.owner or 'undocumented'}",
            f"- Version: {e.version or 'undocumented'}",
            f"- Status codes: {', '.join(e.status_codes) or 'undocumented'}",
            f"- Source: `{e.source_file}`",
            "",
        ]
        if e.parameters:
            lines.append("| Parameter | In | Type | Required | Description |")
            lines.append("|---|---|---|---|---|")
            for p in e.parameters:
                lines.append(
                    f"| {p.name} | {p.location} | {p.type} | {p.required} | {p.description} |"
                )
            lines.append("")
        if e.request_example:
            lines += ["**Request example**", "```json", e.request_example, "```", ""]
        if e.response_example:
            lines += ["**Response example**", "```json", e.response_example, "```", ""]
        lines += ["**cURL**", "```bash", curl_for_endpoint(e), "```", ""]

    for title, value in (
        ("Authentication", result.authentication),
        ("Authorization", result.authorization),
        ("Rate Limits", result.rate_limits),
        ("Pagination", result.pagination),
        ("Versioning", result.versioning),
    ):
        if value:
            lines += [f"## {title}", "", value, ""]

    if result.security_findings:
        lines += ["## Security Findings", ""]
        for f in sorted(result.security_findings, key=lambda f: _SEVERITY_ORDER[f.severity]):
            lines += [
                f"### [{f.severity.upper()}] {f.title}",
                "",
                f"**Category:** {f.category}",
                "",
                f.description,
                "",
                f"**Why it matters:** {f.why_it_matters}",
                "",
                f"**Recommendation:** {f.recommendation}",
                "",
            ]

    if result.missing_information:
        lines += ["## Missing Information", ""]
        lines += [f"- {item}" for item in result.missing_information]
        lines += [""]

    if result.assumptions or result.todos or result.open_questions:
        lines += ["## Notes", ""]
        for label, items in (
            ("Assumptions", result.assumptions),
            ("TODOs", result.todos),
            ("Open Questions", result.open_questions),
        ):
            if items:
                lines.append(f"**{label}:**")
                lines += [f"- {item}" for item in items]
                lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML dashboard
# ---------------------------------------------------------------------------

_SEVERITY_ORDER: dict[FindingSeverity, int] = {"critical": 0, "high": 1, "medium": 2, "low": 3}
_SEVERITY_COLOR = {"critical": "#f87171", "high": "#fb923c", "medium": "#fbbf24", "low": "#60a5fa"}
_METHOD_COLOR = {
    "GET": "#34d399",
    "POST": "#60a5fa",
    "PUT": "#fbbf24",
    "PATCH": "#c084fc",
    "DELETE": "#f87171",
    "HEAD": "#94a3b8",
    "OPTIONS": "#94a3b8",
}

_OWASP_LABELS: dict[str, str] = {
    "authentication": "Broken Authentication",
    "authorization": "Broken Object/Function Level Authorization",
    "input_validation": "Improper Input Validation",
    "sensitive_data_exposure": "Excessive Data Exposure",
    "rate_limiting": "Unrestricted Resource Consumption",
    "replay_protection": "Replay / Idempotency Weakness",
    "https_usage": "Insecure Transport (HTTPS)",
    "token_handling": "Improper Token Handling",
    "secrets": "Hardcoded / Exposed Secrets",
    "pii": "PII Handling",
    "error_leakage": "Improper Error Handling",
    "owasp_api_top_10": "General API Security Misconfiguration",
}


def _esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def _gauge(label: str, value: int, *, color: str = "#8b5cf6") -> str:
    angle = round(value / 100 * 360)
    return f"""
    <div class="gauge">
      <div class="gauge-ring" style="background: conic-gradient({color} {angle}deg, #2a2a35 0deg);">
        <div class="gauge-inner"><span class="gauge-value" data-count="{value}">{value}</span></div>
      </div>
      <div class="gauge-label">{_esc(label)}</div>
    </div>"""


def _bar(label: str, value: int, *, color: str = "#8b5cf6") -> str:
    return f"""
    <div class="bar-row">
      <span class="bar-label">{_esc(label)}</span>
      <div class="bar-track"><div class="bar-fill" style="width:{value}%; background:{color};"></div></div>
      <span class="bar-value">{value}</span>
    </div>"""


def _endpoint_card(e: ApiEndpoint) -> str:
    color = _METHOD_COLOR.get(e.method, "#94a3b8")
    params = "".join(
        f"<tr><td>{_esc(p.name)}</td><td>{_esc(p.location)}</td><td>{_esc(p.type)}</td>"
        f"<td>{'yes' if p.required else 'no'}</td><td>{_esc(p.description)}</td></tr>"
        for p in e.parameters
    )
    return f"""
    <details class="endpoint-card">
      <summary>
        <span class="method-badge" style="background:{color}22;color:{color};border-color:{color}55;">{_esc(e.method)}</span>
        <span class="endpoint-path">{_esc(e.path)}</span>
        {'<span class="auth-badge">🔒 Auth</span>' if e.authentication_required else ""}
        <span class="endpoint-owner">{_esc(e.owner or "unowned")}</span>
      </summary>
      <div class="endpoint-body">
        <p class="endpoint-desc">{_esc(e.description or "No description documented.")}</p>
        {f'<table class="param-table"><thead><tr><th>Name</th><th>In</th><th>Type</th><th>Required</th><th>Description</th></tr></thead><tbody>{params}</tbody></table>' if e.parameters else ""}
        <div class="req-resp-grid">
          {f'<div><h4>Request</h4><pre>{_esc(e.request_example)}</pre></div>' if e.request_example else ""}
          {f'<div><h4>Response</h4><pre>{_esc(e.response_example)}</pre></div>' if e.response_example else ""}
        </div>
        <div class="status-codes">{"".join(f'<span class="status-chip">{_esc(c)}</span>' for c in e.status_codes)}</div>
        <h4>cURL</h4>
        <pre>{_esc(curl_for_endpoint(e))}</pre>
      </div>
    </details>"""


def _finding_card(f: SecurityFinding) -> str:
    color = _SEVERITY_COLOR.get(f.severity, "#94a3b8")
    return f"""
    <details class="finding-card" style="border-left-color:{color};">
      <summary>
        <span class="severity-badge" style="background:{color}22;color:{color};">{_esc(f.severity.upper())}</span>
        <span class="finding-title">{_esc(f.title)}</span>
        <span class="finding-category">{_esc(f.category.replace("_", " "))}</span>
      </summary>
      <div class="finding-body">
        <p>{_esc(f.description)}</p>
        <p><strong>Why it matters:</strong> {_esc(f.why_it_matters)}</p>
        <p><strong>Recommendation:</strong> {_esc(f.recommendation)}</p>
        <p class="confidence">Confidence: {round(f.confidence * 100)}%</p>
      </div>
    </details>"""


def render_html_dashboard(result: ApiIntelligenceResult) -> str:
    """A self-contained, dark-themed HTML dashboard. No external
    stylesheets/scripts/fonts/CDNs — every asset is inline, so the file
    downloads and opens standalone with no network dependency."""
    s = result.scores
    severity_counts = {sev: 0 for sev in _SEVERITY_ORDER}
    for f in result.security_findings:
        severity_counts[f.severity] += 1

    method_counts: dict[str, int] = {}
    for e in result.endpoints:
        method_counts[e.method] = method_counts.get(e.method, 0) + 1

    all_status_codes = sorted({c for e in result.endpoints for c in e.status_codes})

    findings_sorted = sorted(result.security_findings, key=lambda f: _SEVERITY_ORDER[f.severity])

    owasp_rows = "".join(f"""<tr>
          <td>{_esc(label)}</td>
          <td><span class="owasp-count" style="color:{'#f87171' if severity_counts.get('critical',0) or any(f.category==key and f.severity in ('critical','high') for f in result.security_findings) else '#34d399'}">
            {sum(1 for f in result.security_findings if f.category == key)}
          </span></td>
        </tr>""" for key, label in _OWASP_LABELS.items())

    relationship_rows = (
        "".join(
            f'<div class="rel-edge"><span>{_esc(r.from_file)}</span><span class="rel-arrow">&#8594;</span><span>{_esc(r.to_file)}</span></div>'
            for r in result.document_relationships
        )
        or '<p class="empty-note">No internal document links were discovered.</p>'
    )

    missing_html = (
        "".join(f"<li>{_esc(item)}</li>" for item in result.missing_information)
        if result.missing_information
        else '<li class="empty-note">Nothing flagged as missing — treat this as informational, not a certification.</li>'
    )

    file_rows = "".join(
        f'<div class="file-chip">{_esc(f.path)} <span class="file-meta">{f.size_bytes}B · {f.heading_count}h</span></div>'
        for f in result.files_reviewed
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>API Intelligence — {_esc(result.repository_full_name)}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root {{
    --bg: #0a0a0f; --surface: #12121a; --surface-raised: #191922; --line: #24242f;
    --fg: #f4f4f6; --fg-muted: #9a9aab; --accent: #8b5cf6; --accent-2: #60a5fa;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; background: radial-gradient(circle at top, #14141d 0%, var(--bg) 60%);
    color: var(--fg); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
    line-height: 1.5;
  }}
  nav.sticky-nav {{
    position: sticky; top: 0; z-index: 10; display: flex; gap: 4px; overflow-x: auto;
    background: rgba(10,10,15,0.85); backdrop-filter: blur(10px); border-bottom: 1px solid var(--line);
    padding: 12px 24px;
  }}
  nav.sticky-nav a {{
    color: var(--fg-muted); text-decoration: none; font-size: 13px; padding: 6px 12px;
    border-radius: 6px; white-space: nowrap;
  }}
  nav.sticky-nav a:hover {{ background: var(--surface-raised); color: var(--fg); }}
  header.hero {{ padding: 48px 24px 24px; }}
  header.hero h1 {{
    font-size: 28px; margin: 0 0 8px;
    background: linear-gradient(90deg, var(--accent), var(--accent-2));
    -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent;
  }}
  header.hero p {{ color: var(--fg-muted); max-width: 760px; }}
  main {{ padding: 0 24px 64px; max-width: 1180px; margin: 0 auto; }}
  section {{ margin-top: 48px; scroll-margin-top: 64px; }}
  section h2 {{ font-size: 18px; margin-bottom: 16px; display: flex; align-items: center; gap: 8px; }}
  .card {{ background: var(--surface); border: 1px solid var(--line); border-radius: 12px; padding: 20px; }}
  .grid {{ display: grid; gap: 16px; }}
  .grid-4 {{ grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }}
  .grid-2 {{ grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); }}
  .gauge {{ display: flex; flex-direction: column; align-items: center; gap: 8px; }}
  .gauge-ring {{ width: 96px; height: 96px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }}
  .gauge-inner {{ width: 72px; height: 72px; border-radius: 50%; background: var(--surface); display: flex; align-items: center; justify-content: center; }}
  .gauge-value {{ font-size: 20px; font-weight: 700; }}
  .gauge-label {{ font-size: 12px; color: var(--fg-muted); text-align: center; }}
  .bar-row {{ display: flex; align-items: center; gap: 12px; margin-bottom: 10px; }}
  .bar-label {{ width: 140px; font-size: 13px; color: var(--fg-muted); }}
  .bar-track {{ flex: 1; height: 8px; background: var(--surface-raised); border-radius: 4px; overflow: hidden; }}
  .bar-fill {{ height: 100%; border-radius: 4px; transition: width 1s ease; }}
  .bar-value {{ width: 32px; text-align: right; font-size: 13px; }}
  .heatmap {{ display: flex; gap: 8px; flex-wrap: wrap; }}
  .heat-cell {{
    flex: 1; min-width: 120px; border-radius: 10px; padding: 16px; text-align: center;
    border: 1px solid var(--line);
  }}
  .heat-cell .count {{ font-size: 28px; font-weight: 700; }}
  .endpoint-card, .finding-card {{
    background: var(--surface); border: 1px solid var(--line); border-radius: 10px;
    margin-bottom: 10px; overflow: hidden;
  }}
  .finding-card {{ border-left: 4px solid; }}
  .endpoint-card summary, .finding-card summary {{
    cursor: pointer; padding: 14px 16px; display: flex; align-items: center; gap: 10px;
    list-style: none; font-size: 13px;
  }}
  summary::-webkit-details-marker {{ display: none; }}
  .method-badge, .severity-badge {{
    font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 6px; border: 1px solid;
  }}
  .endpoint-path {{ font-family: ui-monospace, monospace; font-size: 13px; }}
  .auth-badge {{ font-size: 11px; color: #fbbf24; }}
  .endpoint-owner, .finding-category {{ margin-left: auto; font-size: 11px; color: var(--fg-muted); }}
  .endpoint-body, .finding-body {{ padding: 0 16px 16px; border-top: 1px solid var(--line); font-size: 13px; color: var(--fg-muted); }}
  .endpoint-body pre, .finding-body pre {{
    background: var(--surface-raised); padding: 12px; border-radius: 8px; overflow-x: auto;
    color: var(--fg); font-size: 12px;
  }}
  .param-table {{ width: 100%; border-collapse: collapse; font-size: 12px; margin: 10px 0; }}
  .param-table th, .param-table td {{ text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--line); }}
  .req-resp-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
  .status-codes {{ display: flex; gap: 6px; margin: 10px 0; }}
  .status-chip {{ background: var(--surface-raised); padding: 2px 8px; border-radius: 6px; font-size: 11px; }}
  table.matrix {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  table.matrix th, table.matrix td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid var(--line); }}
  .rel-edge {{ display: flex; gap: 8px; align-items: center; font-size: 13px; padding: 6px 0; color: var(--fg-muted); }}
  .rel-arrow {{ color: var(--accent); }}
  .file-chip {{ display: inline-flex; gap: 6px; align-items: center; background: var(--surface-raised); border-radius: 8px; padding: 4px 10px; font-size: 12px; margin: 4px; }}
  .file-meta {{ color: var(--fg-muted); }}
  .empty-note {{ color: var(--fg-muted); font-style: italic; }}
  .confidence {{ color: var(--fg-muted); font-size: 12px; }}
  ul.plain {{ padding-left: 18px; }}
  footer {{ text-align: center; color: var(--fg-muted); font-size: 12px; padding: 24px; }}
</style>
</head>
<body>
<nav class="sticky-nav">
  <a href="#summary">Summary</a>
  <a href="#landscape">API Landscape</a>
  <a href="#security-score">Security Score</a>
  <a href="#risk-heatmap">Risk Heatmap</a>
  <a href="#endpoints">Endpoint Explorer</a>
  <a href="#auth-flow">Authentication</a>
  <a href="#status-matrix">Status Codes</a>
  <a href="#owasp">OWASP Coverage</a>
  <a href="#missing">Missing Info</a>
  <a href="#relationships">Dependency Diagram</a>
  <a href="#security-findings">Security Findings</a>
  <a href="#readiness">Readiness</a>
</nav>

<header class="hero">
  <h1>API Intelligence — {_esc(result.repository_full_name)}</h1>
  <p>{_esc(result.executive_summary or "Generated from Markdown documentation only — no source code was analyzed.")}</p>
</header>

<main>
  <section id="summary">
    <h2>Executive Summary</h2>
    <div class="card grid grid-4">
      {_gauge("Overall Readiness", s.overall_readiness_score, color="#8b5cf6")}
      {_gauge("Security", s.security_score, color="#f87171")}
      {_gauge("Doc Completeness", s.documentation_completeness, color="#34d399")}
      {_gauge("API Quality", s.api_quality_score, color="#60a5fa")}
    </div>
  </section>

  <section id="landscape">
    <h2>API Landscape</h2>
    <div class="card grid grid-4">
      <div class="heat-cell"><div class="count">{len(result.endpoints)}</div><div>Endpoints</div></div>
      <div class="heat-cell"><div class="count">{len(result.base_urls)}</div><div>Base URLs</div></div>
      <div class="heat-cell"><div class="count">{len(result.files_reviewed)}</div><div>Markdown Files</div></div>
      <div class="heat-cell"><div class="count">{sum(method_counts.values())}</div><div>Documented Methods</div></div>
    </div>
    <div class="card" style="margin-top:12px;">
      {"".join(_bar(method, count, color=_METHOD_COLOR.get(method, "#8b5cf6")) for method, count in sorted(method_counts.items()))}
    </div>
  </section>

  <section id="security-score">
    <h2>Security Score</h2>
    <div class="card">
      {_bar("Security", s.security_score, color="#f87171")}
      {_bar("Readability", s.readability_score, color="#60a5fa")}
      {_bar("Consistency", s.consistency_score, color="#c084fc")}
    </div>
  </section>

  <section id="risk-heatmap">
    <h2>Risk Heatmap</h2>
    <div class="card heatmap">
      {"".join(f'<div class="heat-cell" style="border-color:{_SEVERITY_COLOR[sev]}55;"><div class="count" style="color:{_SEVERITY_COLOR[sev]}">{count}</div><div>{sev.title()}</div></div>' for sev, count in severity_counts.items())}
    </div>
  </section>

  <section id="endpoints">
    <h2>Endpoint Explorer</h2>
    {"".join(_endpoint_card(e) for e in result.endpoints) or '<p class="empty-note">No endpoints were extracted from the provided documentation.</p>'}
  </section>

  <section id="auth-flow">
    <h2>Authentication Flow</h2>
    <div class="card grid grid-2">
      <div><h4>Authentication</h4><p>{_esc(result.authentication or "Not documented.")}</p></div>
      <div><h4>Authorization</h4><p>{_esc(result.authorization or "Not documented.")}</p></div>
      <div><h4>Rate Limits</h4><p>{_esc(result.rate_limits or "Not documented.")}</p></div>
      <div><h4>Pagination</h4><p>{_esc(result.pagination or "Not documented.")}</p></div>
    </div>
  </section>

  <section id="status-matrix">
    <h2>Status Code Matrix</h2>
    <div class="card">
      <table class="matrix">
        <thead><tr><th>Endpoint</th>{"".join(f"<th>{_esc(c)}</th>" for c in all_status_codes)}</tr></thead>
        <tbody>
          {"".join(
              "<tr><td>" + _esc(f"{e.method} {e.path}") + "</td>" +
              "".join(f'<td>{"✓" if c in e.status_codes else ""}</td>' for c in all_status_codes) +
              "</tr>"
              for e in result.endpoints
          ) or '<tr><td class="empty-note">No endpoints documented.</td></tr>'}
        </tbody>
      </table>
    </div>
  </section>

  <section id="owasp">
    <h2>OWASP API Top 10 Coverage</h2>
    <div class="card">
      <table class="matrix">
        <thead><tr><th>Category</th><th>Findings</th></tr></thead>
        <tbody>{owasp_rows}</tbody>
      </table>
    </div>
  </section>

  <section id="missing">
    <h2>Missing Information</h2>
    <div class="card"><ul class="plain">{missing_html}</ul></div>
  </section>

  <section id="relationships">
    <h2>Dependency Diagram</h2>
    <div class="card">{relationship_rows}</div>
  </section>

  <section id="files">
    <h2>Files Reviewed</h2>
    <div class="card">{file_rows or '<p class="empty-note">No Markdown files were found.</p>'}</div>
  </section>

  <section id="security-findings">
    <h2>Security Findings</h2>
    {"".join(_finding_card(f) for f in findings_sorted) or '<p class="empty-note">No security findings.</p>'}
  </section>

  <section id="recommendations">
    <h2>Recommendations</h2>
    <div class="card"><ul class="plain">{"".join(f"<li>{_esc(f.recommendation)}</li>" for f in findings_sorted) or '<li class="empty-note">None.</li>'}</ul></div>
  </section>

  <section id="readiness">
    <h2>Readiness Score</h2>
    <div class="card grid grid-4">
      {_gauge("Overall Readiness", s.overall_readiness_score, color="#8b5cf6")}
    </div>
  </section>
</main>

<footer>Generated by the GraphForge API Intelligence Agent from Markdown documentation only.</footer>

<script>
  document.querySelectorAll('[data-count]').forEach(function (el) {{
    var target = parseInt(el.getAttribute('data-count'), 10) || 0;
    var current = 0;
    var step = Math.max(1, Math.round(target / 30));
    var timer = setInterval(function () {{
      current += step;
      if (current >= target) {{ current = target; clearInterval(timer); }}
      el.textContent = current;
    }}, 16);
  }});
</script>
</body>
</html>"""


def render_json(result: ApiIntelligenceResult) -> str:
    """Pretty-printed JSON export — a thin wrapper so callers don't reach
    into `model_dump_json` directly and so the export endpoint's format
    dispatch stays uniform across all five output formats."""
    return json.dumps(result.model_dump(), indent=2, default=str)
