"""Schema-shape tests for RFC-001's migration (`42c15cf49ec2`).

Not a destructive alembic upgrade/downgrade run against the shared test
database (see RFC-001.md's Known Limitations for why that's deliberately
left as a manually-verified, not automated-in-CI, step for this pass).
Instead, this asserts the ORM models — which the migration was
autogenerated from and hand-verified to match exactly — define the table
shape Architecture v2.1 requires: the right tables, the joined-table
inheritance chain, and the N-ary Contradiction join table.
"""

from __future__ import annotations

from app.database.base import Base
from app.models.belief import Belief, Hypothesis
from app.models.contradiction import Contradiction, ContradictionParty
from app.models.decision import Decision, Recommendation
from app.models.engineering_artifact import EngineeringArtifact
from app.models.engineering_session import SESSION_STATUSES, TimelineEntry
from app.models.evidence import Evidence
from app.models.participant import AGENT_ROLES, Participant

_EXPECTED_TABLES = {
    "participants",
    "engineering_sessions",
    "engineering_artifacts",
    "timeline_entries",
    "beliefs",
    "evidence",
    "hypotheses",
    "recommendations",
    "decisions",
    "contradictions",
    "contradiction_parties",
}


def test_every_rfc_001_table_is_registered_on_base_metadata():
    assert _EXPECTED_TABLES.issubset(set(Base.metadata.tables))


def test_joined_table_inheritance_subtypes_share_the_artifact_base_primary_key():
    for model in (Belief, Hypothesis, Evidence, Decision, Recommendation, Contradiction):
        pk_columns = {c.name for c in model.__table__.primary_key.columns}
        assert pk_columns == {"id"}, model
        fk_targets = {
            fk.target_fullname for col in model.__table__.columns for fk in col.foreign_keys
        }
        assert "engineering_artifacts.id" in fk_targets, model


def test_contradiction_party_references_the_shared_artifact_base_table():
    """The real, enforced expression of "N-ary, mixed-type disputes" —
    `artifact_id` targets `engineering_artifacts`, not any one concrete
    subtype (Architecture v2.1 §2.2, Δ v2.1)."""
    fk_targets = {
        fk.target_fullname
        for col in ContradictionParty.__table__.columns
        for fk in col.foreign_keys
    }
    assert "engineering_artifacts.id" in fk_targets
    assert "contradictions.id" in fk_targets


def test_contradiction_parties_pair_is_unique():
    constraint_names = {c.name for c in ContradictionParty.__table__.constraints}
    assert "uq_contradiction_parties_pair" in constraint_names


def test_timeline_entries_sequence_is_unique_per_session():
    constraint_names = {c.name for c in TimelineEntry.__table__.constraints}
    assert "uq_timeline_entries_session_sequence" in constraint_names


def test_engineering_artifact_retention_state_is_constrained():
    constraint_names = {c.name for c in EngineeringArtifact.__table__.constraints}
    assert "ck_engineering_artifacts_retention_state" in constraint_names


def test_participant_kind_shape_is_constrained():
    constraint_names = {c.name for c in Participant.__table__.constraints}
    assert "ck_participants_kind_shape" in constraint_names


def test_agent_roles_matches_architecture_v21_section_5_roster():
    assert set(AGENT_ROLES) == {
        "investigator",
        "planner",
        "developer",
        "tester",
        "reviewer",
        "architect",
        "knowledge_curator",
        "production_analyst",
        "mission_coordinator",
    }


def test_session_statuses_matches_architecture_v21_section_31_lifecycle():
    assert set(SESSION_STATUSES) == {
        "orienting",
        "forming_beliefs",
        "investigating",
        "converging",
        "deciding",
        "building",
        "verifying",
        "operating",
        "dormant",
    }


def test_engineering_session_owns_timeline_and_artifacts_by_composition():
    """Cascade delete — Architecture v2.1 §2.2: Session owns its Timeline
    and every Engineering Artifact (composition, not reference)."""
    session_fks = {
        (col.table.name, fk.column.table.name, fk.ondelete)
        for col in TimelineEntry.__table__.columns
        for fk in col.foreign_keys
        if fk.column.table.name == "engineering_sessions"
    }
    assert ("timeline_entries", "engineering_sessions", "CASCADE") in session_fks

    artifact_session_fks = {
        (col.table.name, fk.column.table.name, fk.ondelete)
        for col in EngineeringArtifact.__table__.columns
        for fk in col.foreign_keys
        if fk.column.table.name == "engineering_sessions"
    }
    assert ("engineering_artifacts", "engineering_sessions", "CASCADE") in artifact_session_fks
