"""Unit tests for the SDLC Workflow system.

Covers:
- Workflow model creation
- Workflow service (stage transitions, context building)
- Workflow API DTOs
- Run linking
- Context propagation
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from app.models.run import Run
from app.models.workflow import Workflow
from app.services.workflow_service import (
    STAGE_GOALS,
    STAGE_LABELS,
    STAGES,
    WORKFLOW_TYPE_STAGES,
    _summarize_previous_output,
    build_stage_context,
    next_stage,
    stage_sequence,
)

# No LLM-mocking fixture needed here anymore: create_workflow() no longer
# calls generate_title() synchronously (a real LLM call) — it assigns
# app.agents.title_generation.fallback_title(title) as an instant,
# deterministic placeholder, and the real AI title is generated by a
# background task the router schedules only after the workflow is
# committed (see app.orchestrator.background_execution.
# schedule_title_generation). That background path — and generate_title()
# itself — is covered separately in tests/unit/ai/test_title_generation.py
# and tests/unit/ai/test_background_title_generation.py.


# ---------------------------------------------------------------------------
# Stage definitions tests
# ---------------------------------------------------------------------------


def test_stages_order() -> None:
    assert STAGES == ("planning", "development", "testing", "review")


def test_stage_goals_mapping() -> None:
    assert STAGE_GOALS["planning"] == "plan_freeform"
    assert STAGE_GOALS["development"] == "develop_change_plan"
    assert STAGE_GOALS["testing"] == "plan_tests"
    assert STAGE_GOALS["review"] == "review_pr"


def test_stage_labels() -> None:
    assert STAGE_LABELS["planning"] == "Planning"
    assert STAGE_LABELS["development"] == "Development"
    assert STAGE_LABELS["testing"] == "Testing"
    assert STAGE_LABELS["review"] == "Review"


# ---------------------------------------------------------------------------
# next_stage tests
# ---------------------------------------------------------------------------


def test_next_stage_planning() -> None:
    assert next_stage("planning") == "development"


def test_next_stage_development() -> None:
    assert next_stage("development") == "testing"


def test_next_stage_testing() -> None:
    assert next_stage("testing") == "review"


def test_next_stage_review_is_none() -> None:
    assert next_stage("review") is None


def test_next_stage_unknown() -> None:
    assert next_stage("unknown") is None


# ---------------------------------------------------------------------------
# workflow_type-aware stage registry tests (shared-engine design)
# ---------------------------------------------------------------------------


def test_legacy_sdlc_sequence_is_exactly_stages() -> None:
    """Backward compatibility: the pre-existing 4-stage sequence is never
    reinterpreted — legacy_sdlc is byte-for-byte the old STAGES tuple."""
    assert WORKFLOW_TYPE_STAGES["legacy_sdlc"] == STAGES
    assert stage_sequence("legacy_sdlc") == ("planning", "development", "testing", "review")


def test_planning_sequence_ends_in_engineering_review_not_review() -> None:
    assert stage_sequence("planning") == (
        "planning",
        "development",
        "testing",
        "documentation_planning",
        "engineering_review",
    )
    assert "review" not in stage_sequence("planning")


def test_stage_sequence_unknown_type_falls_back_to_legacy() -> None:
    """A workflow with a not-yet-known workflow_type (or None) is never
    reinterpreted onto the new "planning" stages — falls back to the
    frozen default."""
    assert stage_sequence("some_future_type") == STAGES
    assert stage_sequence(None) == STAGES  # type: ignore[arg-type]


def test_next_stage_respects_workflow_type() -> None:
    assert next_stage("testing", "planning") == "documentation_planning"
    assert next_stage("documentation_planning", "planning") == "engineering_review"
    assert next_stage("engineering_review", "planning") is None
    # legacy_sdlc (the default) is unaffected — proves the two sequences
    # are genuinely independent, not one leaking into the other.
    assert next_stage("testing", "legacy_sdlc") == "review"


def test_engineering_review_stage_metadata_registered() -> None:
    assert STAGE_GOALS["engineering_review"] == "review_readiness"
    assert STAGE_LABELS["engineering_review"] == "Engineering Review"


def test_documentation_planning_stage_metadata_registered() -> None:
    assert STAGE_GOALS["documentation_planning"] == "plan_documentation"
    assert STAGE_LABELS["documentation_planning"] == "Documentation Planning"


# ---------------------------------------------------------------------------
# Context summarization tests
# ---------------------------------------------------------------------------


def _make_run(result: dict | None = None, goal: str = "plan_freeform") -> Run:
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test task",
        goal=goal,
        status="completed",
        created_at=datetime.now(UTC),
    )
    step = MagicMock()
    step.result = result
    step.confidence_score = 0.85
    run.steps = [step]
    return run


def test_summarize_previous_output_empty() -> None:
    run = _make_run(result=None)
    assert _summarize_previous_output(run) == ""


def test_summarize_previous_output_with_summary() -> None:
    run = _make_run(
        result={
            "executive_summary": "Implement JWT auth across all services.",
            "affected_components": ["OrderController", "PaymentService"],
        }
    )
    summary = _summarize_previous_output(run)
    assert "JWT auth" in summary
    assert "OrderController" in summary


def test_summarize_previous_output_multiple_fields() -> None:
    run = _make_run(
        result={
            "executive_summary": "Plan complete.",
            "affected_repositories": ["order-service", "payment-service"],
            "kafka_topics_involved": ["order.created"],
            "risk_considerations": ["Token expiry"],
        }
    )
    summary = _summarize_previous_output(run)
    assert "order-service" in summary
    assert "order.created" in summary
    assert "Token expiry" in summary


def test_summarize_previous_output_no_steps() -> None:
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_freeform",
        status="completed",
        created_at=datetime.now(UTC),
    )
    run.steps = []
    assert _summarize_previous_output(run) == ""


# ---------------------------------------------------------------------------
# build_stage_context tests
# ---------------------------------------------------------------------------


def test_build_stage_context_first_stage() -> None:
    workflow = Workflow(
        id=uuid.uuid4(),
        title="JWT auth",
        current_stage="planning",
        status="in_progress",
    )
    workflow.runs = []
    ctx = build_stage_context(workflow, "JWT auth", "planning")
    assert ctx == "JWT auth"


def test_build_stage_context_second_stage() -> None:
    workflow = Workflow(
        id=uuid.uuid4(),
        title="JWT auth",
        current_stage="development",
        status="in_progress",
    )
    planning_run = _make_run(
        result={"executive_summary": "Plan: implement JWT in all services."},
        goal="plan_freeform",
    )
    planning_run.workflow_stage = "planning"
    planning_run.workflow_id = workflow.id
    workflow.runs = [planning_run]

    ctx = build_stage_context(workflow, "JWT auth", "development")
    assert "JWT auth" in ctx
    assert "Plan: implement JWT in all services." in ctx
    assert "Planning stage" in ctx


def test_build_stage_context_third_stage_accumulates() -> None:
    workflow = Workflow(
        id=uuid.uuid4(),
        title="JWT auth",
        current_stage="testing",
        status="in_progress",
    )
    planning_run = _make_run(
        result={"executive_summary": "Plan: JWT implementation."},
        goal="plan_freeform",
    )
    planning_run.workflow_stage = "planning"
    planning_run.workflow_id = workflow.id
    planning_run.created_at = datetime(2026, 7, 23, 10, 0, tzinfo=UTC)

    dev_run = _make_run(
        result={"executive_summary": "Dev plan: 3 phases, 5 components."},
        goal="develop_change_plan",
    )
    dev_run.workflow_stage = "development"
    dev_run.workflow_id = workflow.id
    dev_run.created_at = datetime(2026, 7, 23, 11, 0, tzinfo=UTC)

    workflow.runs = [planning_run, dev_run]

    ctx = build_stage_context(workflow, "JWT auth", "testing")
    assert "JWT auth" in ctx
    assert "JWT implementation" in ctx
    assert "3 phases, 5 components" in ctx


# ---------------------------------------------------------------------------
# Workflow model tests
# ---------------------------------------------------------------------------


def test_workflow_model_defaults() -> None:
    w = Workflow(
        id=uuid.uuid4(),
        title="Test workflow",
        current_stage="planning",
        status="in_progress",
    )
    assert w.current_stage == "planning"
    assert w.status == "in_progress"


def test_run_model_workflow_fields() -> None:
    wf_id = uuid.uuid4()
    prev_id = uuid.uuid4()
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_freeform",
        status="completed",
        workflow_id=wf_id,
        workflow_stage="planning",
        previous_run_id=prev_id,
    )
    assert run.workflow_id == wf_id
    assert run.workflow_stage == "planning"
    assert run.previous_run_id == prev_id


def test_run_model_workflow_fields_optional() -> None:
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_freeform",
        status="completed",
    )
    assert run.workflow_id is None
    assert run.workflow_stage is None
    assert run.previous_run_id is None


# ---------------------------------------------------------------------------
# Workflow service integration tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_workflow() -> None:
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()

    workflow = await create_workflow(mock_db, title="JWT auth implementation")

    assert workflow.title == "JWT auth implementation"
    assert workflow.current_stage == "planning"
    assert workflow.status == "in_progress"
    mock_db.add.assert_called_once()
    mock_db.flush.assert_awaited_once()


@pytest.mark.asyncio
async def test_advance_workflow_to_development() -> None:
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="planning",
        status="in_progress",
    )

    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_freeform",
        status="completed",
        workflow_stage="planning",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.current_stage == "development"
    assert workflow.status == "in_progress"


@pytest.mark.asyncio
async def test_advance_workflow_to_completed() -> None:
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="review",
        status="in_progress",
    )

    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="review_pr",
        status="completed",
        workflow_stage="review",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.current_stage == "completed"
    assert workflow.status == "completed"


@pytest.mark.asyncio
async def test_create_workflow_defaults_to_planning_type() -> None:
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()

    workflow = await create_workflow(mock_db, title="Add rate limiting")

    assert workflow.workflow_type == "planning"
    assert workflow.current_stage == "planning"


@pytest.mark.asyncio
async def test_create_workflow_rejects_legacy_sdlc_type() -> None:
    """legacy_sdlc is not creatable — it exists only for pre-existing rows."""
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()

    with pytest.raises(AppError) as exc_info:
        await create_workflow(mock_db, title="Old-style run", workflow_type="legacy_sdlc")
    assert exc_info.value.status_code == 400
    assert "invalid_workflow_type" in str(exc_info.value.error_code)


@pytest.mark.asyncio
async def test_create_workflow_rejects_unknown_type() -> None:
    """Arbitrary workflow_type values must be rejected, not silently accepted."""
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()

    with pytest.raises(AppError) as exc_info:
        await create_workflow(mock_db, title="Bad type", workflow_type="foobar")
    assert exc_info.value.status_code == 400


@pytest.mark.asyncio
async def test_advance_planning_workflow_to_awaiting_approval_at_last_stage() -> None:
    """The real bug this exists to fix: a Planning workflow must not
    silently become "completed" the way legacy_sdlc does — it gates on a
    human decision, and current_stage stays put (nothing to advance to)."""
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="engineering_review",
        status="in_progress",
        workflow_type="planning",
    )
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="review_readiness",
        status="completed",
        workflow_stage="engineering_review",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.status == "awaiting_approval"
    assert workflow.current_stage == "engineering_review"  # unchanged, not "completed"


@pytest.mark.asyncio
async def test_advance_planning_workflow_mid_sequence_still_advances_normally() -> None:
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="testing",
        status="in_progress",
        workflow_type="planning",
    )
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_tests",
        status="completed",
        workflow_stage="testing",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.current_stage == "documentation_planning"
    assert workflow.status == "in_progress"


@pytest.mark.asyncio
async def test_advance_planning_workflow_documentation_planning_advances_to_review() -> None:
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="documentation_planning",
        status="in_progress",
        workflow_type="planning",
    )
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_documentation",
        status="completed",
        workflow_stage="documentation_planning",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.current_stage == "engineering_review"
    assert workflow.status == "in_progress"


@pytest.mark.asyncio
async def test_approve_workflow_sets_terminal_status() -> None:
    from app.services.workflow_service import approve_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()
    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="engineering_review",
        status="awaiting_approval",
        workflow_type="planning",
    )
    user_id = uuid.uuid4()

    await approve_workflow(mock_db, workflow, user_id)

    assert workflow.status == "approved"
    assert workflow.approved_by_user_id == user_id
    mock_db.flush.assert_awaited_once()


@pytest.mark.asyncio
async def test_reject_workflow_sets_terminal_status() -> None:
    from app.services.workflow_service import reject_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()
    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="engineering_review",
        status="awaiting_approval",
        workflow_type="planning",
    )

    await reject_workflow(mock_db, workflow)

    assert workflow.status == "rejected"


@pytest.mark.asyncio
async def test_reject_workflow_does_not_set_approver() -> None:
    """Regression guard: rejection has no 'approved by' concept — a future
    change to reject_workflow must not accidentally start setting it."""
    from app.services.workflow_service import reject_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()
    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="engineering_review",
        status="awaiting_approval",
        workflow_type="planning",
    )

    await reject_workflow(mock_db, workflow)

    assert workflow.approved_by_user_id is None


@pytest.mark.asyncio
async def test_advance_workflow_no_advance_on_failure() -> None:
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Test",
        current_stage="planning",
        status="in_progress",
    )

    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="plan_freeform",
        status="failed",
        workflow_stage="planning",
    )

    await advance_workflow(mock_db, workflow, run)

    # Should not advance
    assert workflow.current_stage == "planning"


# ---------------------------------------------------------------------------
# API DTO tests
# ---------------------------------------------------------------------------


def test_workflow_api_create_request_validation() -> None:
    from app.api.v1.routers.workflows import CreateWorkflowRequest

    req = CreateWorkflowRequest(title="JWT auth")
    assert req.title == "JWT auth"
    assert req.model is None


def test_workflow_api_create_request_accepts_multi_paragraph_brief() -> None:
    """Regression: NewWorkflowPage's textarea invites a full engineering
    brief, not a short title — a real ~700 char multi-paragraph objective
    (requirements list, output schema, constraints) used to fail with a
    generic "Request validation failed." at the old 512-char cap."""
    from app.api.v1.routers.workflows import CreateWorkflowRequest

    brief = (
        "Project: etl-customer-orders\n\n"
        "We receive daily customer and order CSV files.\n\n"
        "Add a new report that calculates the Top 10 customers by total "
        "purchase amount for each month.\n\n"
        "Requirements\n"
        "- Use existing customer and orders datasets.\n"
        "- Ignore cancelled orders.\n"
        "- Ignore refunded orders.\n"
        "- Aggregate by calendar month.\n"
        "- Output should contain: customer_id, customer_name, month, "
        "total_sales, rank.\n\n"
        "Store the output as Parquet. Use the existing ETL architecture. "
        "Reuse existing transformations whenever possible. Maintain "
        "backward compatibility.\n\n"
        "Generate an implementation plan only. Do not generate code."
    )
    assert len(brief) > 512

    req = CreateWorkflowRequest(title=brief)
    assert req.title == brief


def test_workflow_api_create_request_rejects_title_over_8000_chars() -> None:
    from pydantic import ValidationError

    from app.api.v1.routers.workflows import CreateWorkflowRequest

    with pytest.raises(ValidationError):
        CreateWorkflowRequest(title="x" * 8001)


def test_workflow_api_continue_request_validation() -> None:
    from app.api.v1.routers.workflows import ContinueWorkflowRequest

    req = ContinueWorkflowRequest()
    assert req.model is None


def test_workflow_api_detail_response_shape() -> None:
    from app.api.v1.routers.workflows import (
        WorkflowDetailResponse,
        WorkflowRunResponse,
        WorkflowStageResponse,
    )

    stage = WorkflowStageResponse(
        stage="planning",
        label="Planning",
        status="completed",
        run_id="run-uuid",
    )
    run_item = WorkflowRunResponse(
        run_id="run-uuid",
        goal="plan_freeform",
        status="completed",
        workflow_stage="planning",
        confidence_score=0.85,
        started_at="2026-07-23T10:00:00Z",
        completed_at="2026-07-23T10:01:00Z",
        created_at="2026-07-23T10:00:00Z",
    )
    detail = WorkflowDetailResponse(
        workflow_id="wf-uuid",
        title="JWT auth",
        original_prompt="Implement JWT authentication across all microservices.",
        workflow_type="planning",
        current_stage="development",
        status="in_progress",
        stages=[stage],
        runs=[run_item],
        created_at="2026-07-23T10:00:00Z",
        updated_at="2026-07-23T10:01:00Z",
    )
    assert detail.workflow_id == "wf-uuid"
    assert detail.workflow_type == "planning"
    assert detail.stages[0].stage == "planning"
    assert detail.runs[0].confidence_score == 0.85
    # Never approved — defaults to None, not required at construction.
    assert detail.approved_by is None

    approved_detail = WorkflowDetailResponse(
        workflow_id="wf-uuid",
        title="JWT auth",
        original_prompt="Implement JWT authentication across all microservices.",
        workflow_type="planning",
        current_stage="engineering_review",
        status="approved",
        stages=[stage],
        runs=[run_item],
        created_at="2026-07-23T10:00:00Z",
        updated_at="2026-07-23T10:01:00Z",
        approved_by="Jane Doe",
    )
    assert approved_detail.approved_by == "Jane Doe"


def test_workflow_api_create_request_defaults_to_planning() -> None:
    from app.api.v1.routers.workflows import CreateWorkflowRequest

    req = CreateWorkflowRequest(title="JWT auth")
    assert req.workflow_type == "planning"


def test_workflow_api_approval_response_shape() -> None:
    from app.api.v1.routers.workflows import WorkflowApprovalResponse

    resp = WorkflowApprovalResponse(workflow_id="wf-uuid", status="approved")
    assert resp.workflow_id == "wf-uuid"
    assert resp.status == "approved"


# ---------------------------------------------------------------------------
# Phase 5 — auto_execution workflow registration & terminal behavior
# ---------------------------------------------------------------------------


def test_auto_execution_stage_sequence() -> None:
    """auto_execution is registered with the approved 6-stage sequence."""
    assert stage_sequence("auto_execution") == (
        "generate_code",
        "create_branch",
        "commit_changes",
        "run_tests",
        "create_pull_request",
        "ai_pr_review",
    )


def test_auto_execution_stage_goals_registered() -> None:
    assert STAGE_GOALS["generate_code"] == "generate_code"
    assert STAGE_GOALS["create_branch"] == "create_branch"
    assert STAGE_GOALS["commit_changes"] == "commit_changes"
    assert STAGE_GOALS["run_tests"] == "run_tests"
    assert STAGE_GOALS["create_pull_request"] == "create_pull_request"
    # ai_pr_review reuses the existing Review Agent goal
    assert STAGE_GOALS["ai_pr_review"] == "review_pr"


def test_auto_execution_stage_labels_registered() -> None:
    assert STAGE_LABELS["generate_code"] == "Generate Code"
    assert STAGE_LABELS["create_branch"] == "Create Branch"
    assert STAGE_LABELS["commit_changes"] == "Commit Changes"
    assert STAGE_LABELS["run_tests"] == "Run Tests"
    assert STAGE_LABELS["create_pull_request"] == "Create Pull Request"
    assert STAGE_LABELS["ai_pr_review"] == "AI PR Review"


def test_auto_execution_is_creatable() -> None:
    from app.services.workflow_service import CREATABLE_WORKFLOW_TYPES

    assert "auto_execution" in CREATABLE_WORKFLOW_TYPES


def test_auto_execution_next_stage_sequence() -> None:
    assert next_stage("generate_code", "auto_execution") == "create_branch"
    assert next_stage("create_branch", "auto_execution") == "commit_changes"
    assert next_stage("commit_changes", "auto_execution") == "run_tests"
    assert next_stage("run_tests", "auto_execution") == "create_pull_request"
    assert next_stage("create_pull_request", "auto_execution") == "ai_pr_review"
    assert next_stage("ai_pr_review", "auto_execution") is None


# ---------------------------------------------------------------------------
# Phase 5 — TERMINAL_BEHAVIOR data-driven registry
# ---------------------------------------------------------------------------


def test_terminal_behavior_registry_values() -> None:
    from app.services.workflow_service import TERMINAL_BEHAVIOR

    assert TERMINAL_BEHAVIOR["planning"] == "awaiting_approval"
    assert TERMINAL_BEHAVIOR["auto_execution"] == "completed"
    assert TERMINAL_BEHAVIOR["legacy_sdlc"] == "completed"


@pytest.mark.asyncio
async def test_advance_auto_execution_workflow_last_stage_completes() -> None:
    """auto_execution completes (not awaiting_approval) at its last stage."""
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Execute blueprint",
        current_stage="ai_pr_review",
        status="in_progress",
        workflow_type="auto_execution",
    )
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="review_pr",
        status="completed",
        workflow_stage="ai_pr_review",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.status == "completed"
    assert workflow.current_stage == "completed"


@pytest.mark.asyncio
async def test_advance_auto_execution_workflow_mid_sequence() -> None:
    """auto_execution advances normally between stages."""
    from app.services.workflow_service import advance_workflow

    mock_db = AsyncMock()
    mock_db.flush = AsyncMock()

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Execute blueprint",
        current_stage="create_branch",
        status="in_progress",
        workflow_type="auto_execution",
    )
    run = Run(
        id=uuid.uuid4(),
        subject_id="freetext:test",
        subject_type="freetext",
        display_name="Test",
        goal="create_branch",
        status="completed",
        workflow_stage="create_branch",
    )

    await advance_workflow(mock_db, workflow, run)

    assert workflow.current_stage == "commit_changes"
    assert workflow.status == "in_progress"


# ---------------------------------------------------------------------------
# Phase 5 — create_workflow source_workflow_id validation
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_auto_execution_requires_source_workflow_id() -> None:
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()

    with pytest.raises(AppError) as exc_info:
        await create_workflow(mock_db, title="Auto exec", workflow_type="auto_execution")
    assert exc_info.value.status_code == 400
    assert exc_info.value.error_code == "missing_source_workflow"


@pytest.mark.asyncio
async def test_create_auto_execution_rejects_nonexistent_source() -> None:
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()
    mock_db.get = AsyncMock(return_value=None)

    with pytest.raises(AppError) as exc_info:
        await create_workflow(
            mock_db,
            title="Auto exec",
            workflow_type="auto_execution",
            source_workflow_id=uuid.uuid4(),
        )
    assert exc_info.value.status_code == 400
    assert exc_info.value.error_code == "source_workflow_not_found"


@pytest.mark.asyncio
async def test_create_auto_execution_rejects_non_planning_source() -> None:
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    source = Workflow(
        id=uuid.uuid4(),
        title="Source",
        current_stage="completed",
        status="approved",
        workflow_type="legacy_sdlc",
    )
    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()
    mock_db.get = AsyncMock(return_value=source)

    with pytest.raises(AppError) as exc_info:
        await create_workflow(
            mock_db,
            title="Auto exec",
            workflow_type="auto_execution",
            source_workflow_id=source.id,
        )
    assert exc_info.value.status_code == 400
    assert exc_info.value.error_code == "source_workflow_wrong_type"


@pytest.mark.asyncio
async def test_create_auto_execution_rejects_unapproved_source() -> None:
    from app.core.exceptions import AppError
    from app.services.workflow_service import create_workflow

    source = Workflow(
        id=uuid.uuid4(),
        title="Source",
        current_stage="engineering_review",
        status="awaiting_approval",
        workflow_type="planning",
    )
    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()
    mock_db.get = AsyncMock(return_value=source)

    with pytest.raises(AppError) as exc_info:
        await create_workflow(
            mock_db,
            title="Auto exec",
            workflow_type="auto_execution",
            source_workflow_id=source.id,
        )
    assert exc_info.value.status_code == 400
    assert exc_info.value.error_code == "source_workflow_not_approved"


@pytest.mark.asyncio
async def test_create_auto_execution_succeeds_with_approved_planning_source() -> None:
    from app.services.workflow_service import create_workflow

    source = Workflow(
        id=uuid.uuid4(),
        title="Blueprint",
        current_stage="engineering_review",
        status="approved",
        workflow_type="planning",
    )
    mock_db = AsyncMock()
    mock_db.add = MagicMock()
    mock_db.flush = AsyncMock()
    mock_db.get = AsyncMock(return_value=source)

    workflow = await create_workflow(
        mock_db,
        title="Execute blueprint",
        workflow_type="auto_execution",
        source_workflow_id=source.id,
    )
    assert workflow.workflow_type == "auto_execution"
    assert workflow.source_workflow_id == source.id
    assert workflow.current_stage == "generate_code"
    assert workflow.status == "in_progress"


# ---------------------------------------------------------------------------
# Phase 5 — cross-workflow context (build_stage_context with source)
# ---------------------------------------------------------------------------


def test_build_stage_context_with_source_workflow() -> None:
    """auto_execution gets context from source blueprint runs."""
    source = Workflow(
        id=uuid.uuid4(),
        title="Blueprint",
        current_stage="engineering_review",
        status="approved",
        workflow_type="planning",
    )
    dev_run = _make_run(
        result={
            "executive_summary": "Implement rate limiter in 3 phases.",
            "affected_repositories": ["api-gateway"],
        },
        goal="develop_change_plan",
    )
    dev_run.workflow_stage = "development"
    dev_run.workflow_id = source.id
    dev_run.created_at = datetime(2026, 7, 23, 10, 0, tzinfo=UTC)
    source.runs = [dev_run]

    workflow = Workflow(
        id=uuid.uuid4(),
        title="Execute blueprint",
        current_stage="generate_code",
        status="in_progress",
        workflow_type="auto_execution",
        source_workflow_id=source.id,
    )
    workflow.runs = []

    ctx = build_stage_context(
        workflow,
        original_request="Execute blueprint",
        target_stage="generate_code",
        source_workflow=source,
    )
    assert "Execute blueprint" in ctx
    assert "rate limiter in 3 phases" in ctx
    assert "Blueprint context from Development stage" in ctx
    assert "api-gateway" in ctx


def test_build_stage_context_without_source_unchanged() -> None:
    """Planning workflows (no source) work exactly as before."""
    workflow = Workflow(
        id=uuid.uuid4(),
        title="JWT auth",
        current_stage="development",
        status="in_progress",
        workflow_type="planning",
    )
    planning_run = _make_run(
        result={"executive_summary": "Plan: implement JWT."},
        goal="plan_freeform",
    )
    planning_run.workflow_stage = "planning"
    planning_run.workflow_id = workflow.id
    workflow.runs = [planning_run]

    ctx = build_stage_context(workflow, "JWT auth", "development")
    assert "JWT auth" in ctx
    assert "implement JWT" in ctx
    # No "Blueprint context" header — no source workflow
    assert "Blueprint context" not in ctx


# ---------------------------------------------------------------------------
# Run API DTO with workflow fields
# ---------------------------------------------------------------------------


def test_run_detail_response_includes_workflow_fields() -> None:
    from app.api.v1.routers.agent_runs import RunDetailResponse, SubjectResponse

    resp = RunDetailResponse(
        run_id="run-uuid",
        goal="plan_freeform",
        status="completed",
        subject=SubjectResponse(
            subject_id="freetext:test", subject_type="freetext", display_name="Test"
        ),
        model=None,
        error_message=None,
        started_at="2026-07-23T10:00:00Z",
        completed_at="2026-07-23T10:01:00Z",
        created_at="2026-07-23T10:00:00Z",
        steps=[],
        workflow_id="wf-uuid",
        workflow_stage="planning",
        previous_run_id="prev-uuid",
    )
    assert resp.workflow_id == "wf-uuid"
    assert resp.workflow_stage == "planning"
    assert resp.previous_run_id == "prev-uuid"


def test_run_list_item_includes_workflow_fields() -> None:
    from app.api.v1.routers.agent_runs import RunListItem, SubjectResponse

    item = RunListItem(
        run_id="run-uuid",
        goal="plan_freeform",
        status="completed",
        subject=SubjectResponse(
            subject_id="freetext:test", subject_type="freetext", display_name="Test"
        ),
        started_at=None,
        completed_at=None,
        created_at="2026-07-23T10:00:00Z",
        confidence_score=0.85,
        workflow_id="wf-uuid",
        workflow_stage="planning",
    )
    assert item.workflow_id == "wf-uuid"


def test_run_list_item_workflow_fields_optional() -> None:
    from app.api.v1.routers.agent_runs import RunListItem, SubjectResponse

    item = RunListItem(
        run_id="run-uuid",
        goal="plan_freeform",
        status="completed",
        subject=SubjectResponse(
            subject_id="freetext:test", subject_type="freetext", display_name="Test"
        ),
        started_at=None,
        completed_at=None,
        created_at="2026-07-23T10:00:00Z",
        confidence_score=None,
    )
    assert item.workflow_id is None
    assert item.workflow_stage is None


# ---------------------------------------------------------------------------
# Phase 5 PR #6 — router subject resolution for ai_pr_review
# ---------------------------------------------------------------------------


def _workflow_with_runs(runs: list, title: str = "Add caching layer") -> object:
    # A plain SimpleNamespace, not a real Workflow model instance:
    # `_resolve_stage_subject` (via get_stage_result) only ever reads
    # `.title` and iterates `.runs` — assigning fake Run objects to a real
    # Workflow.runs relationship trips SQLAlchemy's ORM backref machinery,
    # which fakes lacking `_sa_instance_state` can't satisfy.
    from types import SimpleNamespace

    return SimpleNamespace(id=uuid.uuid4(), title=title, runs=runs)


def _pr_result_run(pull_request_id: str, title: str = "feat: add caching") -> object:
    from types import SimpleNamespace

    step = SimpleNamespace(
        result={
            "goal": "create_pull_request",
            "pull_request_id": pull_request_id,
            "github_pr_number": 7,
            "title": title,
        }
    )
    return SimpleNamespace(
        workflow_stage="create_pull_request",
        status="completed",
        steps=[step],
        created_at=datetime.now(UTC),
    )


def test_resolve_stage_subject_uses_freetext_for_non_review_stages() -> None:
    from app.api.v1.routers.workflows import _resolve_stage_subject

    workflow = _workflow_with_runs([])
    subject = _resolve_stage_subject(workflow, "run_tests", "some enriched context")

    assert subject.subject_type == "freetext"


def test_resolve_stage_subject_builds_pr_subject_for_ai_pr_review() -> None:
    from app.api.v1.routers.workflows import _resolve_stage_subject

    pr_id = str(uuid.uuid4())
    workflow = _workflow_with_runs([_pr_result_run(pr_id)])
    subject = _resolve_stage_subject(workflow, "ai_pr_review", "unused")

    assert subject.subject_type == "pull_request"
    assert subject.subject_id == f"pr:{pr_id}"
    assert subject.display_name == "feat: add caching"


def test_resolve_stage_subject_ai_pr_review_without_pr_result_raises() -> None:
    from app.api.v1.routers.workflows import _resolve_stage_subject
    from app.core.exceptions import AppError

    workflow = _workflow_with_runs([])

    with pytest.raises(AppError) as exc_info:
        _resolve_stage_subject(workflow, "ai_pr_review", "unused")

    assert exc_info.value.error_code == "missing_pull_request"


# ---------------------------------------------------------------------------
# approved_by — batch approver-name resolution
# ---------------------------------------------------------------------------


def test_workflow_list_item_approved_by_defaults_to_none() -> None:
    from app.api.v1.routers.workflows import WorkflowListItem

    item = WorkflowListItem(
        workflow_id="wf-uuid",
        title="JWT auth",
        workflow_type="planning",
        current_stage="engineering_review",
        status="awaiting_approval",
        stages=[],
        created_at="2026-07-23T10:00:00Z",
        updated_at="2026-07-23T10:01:00Z",
    )
    assert item.approved_by is None

    approved_item = WorkflowListItem(
        workflow_id="wf-uuid",
        title="JWT auth",
        workflow_type="planning",
        current_stage="engineering_review",
        status="approved",
        stages=[],
        created_at="2026-07-23T10:00:00Z",
        updated_at="2026-07-23T10:01:00Z",
        approved_by="Jane Doe",
    )
    assert approved_item.approved_by == "Jane Doe"


@pytest.mark.asyncio
async def test_resolve_approver_names_batches_single_query() -> None:
    from types import SimpleNamespace

    from app.api.v1.routers.workflows import _resolve_approver_names

    user_a = uuid.uuid4()
    user_b = uuid.uuid4()
    workflows = [
        Workflow(id=uuid.uuid4(), title="X", workflow_type="planning", approved_by_user_id=user_a),
        Workflow(id=uuid.uuid4(), title="Y", workflow_type="planning", approved_by_user_id=user_b),
        # Same approver twice — must not appear twice in the query's IN clause.
        Workflow(id=uuid.uuid4(), title="Z", workflow_type="planning", approved_by_user_id=user_a),
        # Never approved — excluded from the lookup entirely.
        Workflow(id=uuid.uuid4(), title="W", workflow_type="planning"),
    ]

    rows = [
        SimpleNamespace(id=user_a, full_name="Jane Doe"),
        SimpleNamespace(id=user_b, full_name="John Smith"),
    ]
    mock_result = MagicMock()
    mock_result.all.return_value = rows
    mock_db = AsyncMock()
    mock_db.execute = AsyncMock(return_value=mock_result)

    names = await _resolve_approver_names(mock_db, workflows)

    assert mock_db.execute.await_count == 1
    assert names == {user_a: "Jane Doe", user_b: "John Smith"}


@pytest.mark.asyncio
async def test_resolve_approver_names_skips_query_when_none_approved() -> None:
    from app.api.v1.routers.workflows import _resolve_approver_names

    workflows = [Workflow(id=uuid.uuid4(), title="X", workflow_type="planning")]
    mock_db = AsyncMock()
    mock_db.execute = AsyncMock()

    names = await _resolve_approver_names(mock_db, workflows)

    assert names == {}
    mock_db.execute.assert_not_awaited()
