"""Workflow Reports API — the high-level HTML reports generated by
app.agents.report_generation when a Planning workflow is approved.

Read-only: nothing here creates or edits a report directly (that happens
only via the approve_workflow dispatch) or its content, only lists/fetches
what the report_generation agent already produced.
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.v1.dependencies import get_current_user
from app.core.exceptions import NotFoundError
from app.database.session import get_db_session
from app.models.user import User
from app.models.workflow import Workflow
from app.models.workflow_report import WorkflowReport

router = APIRouter(prefix="/reports", tags=["reports"])


class ReportSummary(BaseModel):
    id: str
    workflow_id: str
    workflow_title: str
    title: str
    status: str
    error_message: str | None
    created_at: str
    completed_at: str | None


class ReportDetail(ReportSummary):
    html_content: str | None


def _iso(dt: object) -> str | None:
    return dt.isoformat() if dt is not None else None  # type: ignore[union-attr]


def _to_summary(report: WorkflowReport) -> ReportSummary:
    return ReportSummary(
        id=str(report.id),
        workflow_id=str(report.workflow_id),
        workflow_title=report.workflow.title if report.workflow else report.title,
        title=report.title,
        status=report.status,
        error_message=report.error_message,
        created_at=_iso(report.created_at) or "",
        completed_at=_iso(report.completed_at),
    )


@router.get("", response_model=list[ReportSummary], summary="List generated workflow reports")
async def list_reports(
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session),
) -> list[ReportSummary]:
    """Reports for workflows this user owns, newest first. Mirrors
    Workflow's own ownership rule (workflow.user_id is None or == user.id)
    — a report has no owner of its own, it inherits its workflow's."""
    result = await db.execute(
        select(WorkflowReport)
        .join(Workflow, WorkflowReport.workflow_id == Workflow.id)
        .options(selectinload(WorkflowReport.workflow))
        .where((Workflow.user_id.is_(None)) | (Workflow.user_id == user.id))
        .order_by(WorkflowReport.created_at.desc())
    )
    reports = result.scalars().all()
    return [_to_summary(r) for r in reports]


@router.get(
    "/{report_id}", response_model=ReportDetail, summary="Fetch one report's full HTML content"
)
async def get_report(
    report_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session),
) -> ReportDetail:
    try:
        rid = uuid.UUID(report_id)
    except ValueError as exc:
        raise NotFoundError(f"Invalid report_id: {report_id}") from exc

    result = await db.execute(
        select(WorkflowReport)
        .options(selectinload(WorkflowReport.workflow))
        .where(WorkflowReport.id == rid)
    )
    report = result.scalar_one_or_none()
    # Not found and not owned fail identically — same IDOR-avoidance
    # rationale as Workflow's own _check_workflow_owned.
    if report is None or not (
        report.workflow is None
        or report.workflow.user_id is None
        or report.workflow.user_id == user.id
    ):
        raise NotFoundError(f"Report '{report_id}' not found.")

    return ReportDetail(
        **_to_summary(report).model_dump(),
        html_content=report.html_content,
    )
