"""Workflow Reports API — the high-level HTML reports generated by
app.agents.report_generation when a Planning workflow is approved.

Nothing here creates or edits a report's content (that happens only via
the approve_workflow dispatch) — these routes list and fetch what the
report_generation agent already produced, plus delete one outright. A
report is never mutated in place, so "delete" is the only write: the
stored document always stays exactly what it was when a decision was made
against it, right up until it is removed.
"""

from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.api.v1.dependencies import get_current_user
from app.core.exceptions import NotFoundError
from app.database.session import get_db_session
from app.models.user import User
from app.models.workflow import Workflow
from app.models.workflow_report import WorkflowReport

router = APIRouter(prefix="/reports", tags=["reports"])


class ReportSummary(BaseModel):
    id: str
    workflow_id: str
    workflow_title: str
    title: str
    # `Workflow.original_prompt` — the complete, unmodified request the
    # user actually submitted. A report is the answer to *that*, not a
    # record of the workflow machinery that produced it, so it's what the
    # Reports list leads with; `title` (an AI-generated 5-10 word summary
    # of the same prompt) and `workflow_title` are the short labels.
    # Empty string only for a report whose workflow row has since been
    # removed — never null, so the client has no second empty case to
    # handle beyond "no text".
    request: str
    status: str
    error_message: str | None
    created_at: str
    completed_at: str | None


class ReportDetail(ReportSummary):
    html_content: str | None
    # Report V2 Phase 2 (ADR 0024) — the authoritative, deterministic
    # representation the frontend renders through real components (see
    # frontend/src/components/report/). `html_content` above is kept only
    # as a fallback for older reports / any consumer still reading it
    # directly. `None` for a report generated before this field existed.
    view_model: dict[str, Any] | None


def _iso(dt: object) -> str | None:
    return dt.isoformat() if dt is not None else None  # type: ignore[union-attr]


def _to_summary(report: WorkflowReport) -> ReportSummary:
    return ReportSummary(
        id=str(report.id),
        workflow_id=str(report.workflow_id),
        workflow_title=report.workflow.title if report.workflow else report.title,
        request=report.workflow.original_prompt if report.workflow else "",
        title=report.title,
        status=report.status,
        error_message=report.error_message,
        created_at=_iso(report.created_at) or "",
        completed_at=_iso(report.completed_at),
    )


@router.get("", response_model=list[ReportSummary], summary="List generated workflow reports")
async def list_reports(
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session),
) -> list[ReportSummary]:
    """Reports for workflows this user owns, newest first. Mirrors
    Workflow's own ownership rule (workflow.user_id is None or == user.id)
    — a report has no owner of its own, it inherits its workflow's."""
    result = await db.execute(
        select(WorkflowReport)
        .join(Workflow, WorkflowReport.workflow_id == Workflow.id)
        .options(selectinload(WorkflowReport.workflow))
        .where((Workflow.user_id.is_(None)) | (Workflow.user_id == user.id))
        .order_by(WorkflowReport.created_at.desc())
    )
    reports = result.scalars().all()
    return [_to_summary(r) for r in reports]


async def _load_owned_report(report_id: str, user: User, db: AsyncSession) -> WorkflowReport:
    """The one place a report is resolved by id and checked for ownership.

    A malformed id, a missing report, and someone else's report all raise
    the identical NotFoundError — the same IDOR-avoidance rationale as
    Workflow's own `_check_workflow_owned`, and the reason this is a
    shared helper rather than copied into each route: a second copy is a
    second chance to leak existence by answering one of the three cases
    differently.
    """
    try:
        rid = uuid.UUID(report_id)
    except ValueError as exc:
        raise NotFoundError(f"Report '{report_id}' not found.") from exc

    result = await db.execute(
        select(WorkflowReport)
        .options(selectinload(WorkflowReport.workflow))
        .where(WorkflowReport.id == rid)
    )
    report = result.scalar_one_or_none()
    if report is None or not (
        report.workflow is None
        or report.workflow.user_id is None
        or report.workflow.user_id == user.id
    ):
        raise NotFoundError(f"Report '{report_id}' not found.")
    return report


@router.get(
    "/{report_id}", response_model=ReportDetail, summary="Fetch one report's full HTML content"
)
async def get_report(
    report_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session),
) -> ReportDetail:
    report = await _load_owned_report(report_id, user, db)
    return ReportDetail(
        **_to_summary(report).model_dump(),
        html_content=report.html_content,
        view_model=report.view_model,
    )


@router.delete("/{report_id}", status_code=204, summary="Delete one generated report")
async def delete_report(
    report_id: str,
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db_session),
) -> None:
    """Delete a generated report.

    Removes only the report row — the workflow that produced it, its stage
    runs, and their evidence trails are all untouched, and the same
    workflow can be reported on again. That is the whole difference from
    DELETE /workflows/{id}, which exists to destroy the investigation
    itself.

    `WorkflowReport.run_id` is the report_generation agent's own Run,
    referenced ON DELETE SET NULL from the other side; deleting the report
    never removes that Run, so the report's own generation cost and
    evidence stay in the run history where the rest of the audit trail
    lives.
    """
    report = await _load_owned_report(report_id, user, db)
    await db.delete(report)
    await db.commit()
