"""Report Generation Agent — goal=generate_report.

Runs once, when a human approves a Planning workflow's blueprint (see the
dispatch in api/v1/routers/workflows.py's approve_workflow).

Report V2 Phase 2 (ADR 0024) rewrite: this agent used to hand every
completed stage's raw context to one LLM call and ask it to synthesize a
whole self-contained HTML document — the LLM decided both content and
presentation, and never saw the persisted `reasoning_summary` at all (see
the ADR's §1/§2 audit). It no longer does either.

The new shape:

    fetch_all_stage_bundles(workflow)
      -> build_report_view_model(workflow, bundles)   [deterministic, no LLM]
      -> one LLM call: executive_summary only, prompted with the
         view model's OWN already-decided facts, nothing else
      -> AgentOutput.result = {"title", "view_model", "html"}

`view_model` (see `app.agents.report_generation.view_model.to_json_dict`)
is the authoritative representation the frontend renders through real
deterministic components — see `frontend/src/components/report/`.
`html` is kept only as a minimal plain-text-ish fallback (never the
primary rendering path, never LLM-authored structure) for any consumer
that still expects the legacy field; it is derived from the view model by
code, not generated by the LLM.

Architectural rule (ADR §13, restated here since this is the one place it
could be violated): the LLM decides *only* the wording of
`executive_summary`. It never decides whether a hypothesis, contradiction,
badge, or section appears — that was already decided before this agent's
one LLM call is even made.
"""

from __future__ import annotations

import dataclasses
import logging
from html import escape
from pathlib import Path
from typing import Any

from app.agents._contract import AgentContext, AgentOutput, Confidence, Evidence
from app.agents.llm import invoke_llm_json, stage_for
from app.agents.prompt_utils import parse_json_response, render_prompt_template
from app.agents.report_generation import data_plumbing as dp
from app.agents.report_generation.view_model import (
    ReportViewModel,
    build_report_view_model,
    to_json_dict,
)
from app.core.exceptions import AppError

logger = logging.getLogger(__name__)

_PROMPT_VERSION = "2.0"
_PROMPT_DIR = Path(__file__).parent / "prompts"
_MAX_CONTEXT_CHARS = 4_000

STAGE_GENERATION_STAGE = "report_generation"


class ReportGenerationLLMError(AppError):
    status_code = 502
    error_code = "report_generation_llm_error"


class ReportGenerationExecutionError(AppError):
    status_code = 400
    error_code = "report_generation_requires_workflow"


_SYSTEM_PROMPT = (
    "You are a Principal Engineer writing a short executive summary from "
    "already-decided facts. Respond ONLY with valid JSON matching the "
    "requested schema. Do not include markdown fences or commentary "
    "outside the JSON object."
)


async def _call_llm(
    user_prompt: str,
    model: str | None,
    stage: str,
    metadata_out: dict[str, Any] | None,
    context: AgentContext,
) -> str:
    """Delegates to the shared `app.agents.llm.invoke_llm_json` — kept as a
    module-level function so tests can patch it the same way every other
    agent's `_call_llm` is patched."""
    return await invoke_llm_json(
        system_prompt=_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        stage=stage,
        model=model,
        error_cls=ReportGenerationLLMError,
        metadata_out=metadata_out,
        context=context,
    )


def _summary_prompt_facts(model: ReportViewModel) -> str:
    """The ONLY input the executive-summary LLM call ever sees — a plain-
    text rendering of facts `build_report_view_model` already decided.
    Nothing here is re-derived; every line is a direct read of an already-
    built `ReportViewModel` field. Deliberately excludes prose evidence
    text and the full timeline (the summary doesn't need per-step detail,
    and keeping this short keeps the one LLM call cheap)."""
    lines = [f"Question under investigation: {model.header.question}"]
    if model.header.repository:
        lines.append(f"Repository: {model.header.repository}")
    lines.append(f"Readiness: {model.header.readiness.value}")
    if model.confidence.current is not None:
        lines.append(f"Current confidence: {round(model.confidence.current * 100)}%")
    lines.append(f"Confidence trend: {model.confidence.summary_sentence}")

    state = model.hypotheses.synthesis_state
    lines.append(f"Reasoning synthesis state: {state.value}")
    if state.value == "completed" and model.hypotheses.items:
        top = model.hypotheses.items[0]
        lines.append(
            f"Strongest hypothesis ({round(top.entry.confidence * 100)}% confidence, "
            f"{top.entry.status.value}): {top.entry.statement}"
        )
    elif state.value == "completed_empty":
        lines.append("The investigation converged without competing hypotheses.")
    elif state.value == "failed":
        lines.append(
            "Reasoning synthesis failed for this investigation — evidence-only findings only."
        )
    elif state.value == "not_run":
        lines.append("Reasoning synthesis was not recorded for this investigation.")

    if model.contradictions.items:
        c = model.contradictions.items[0]
        lines.append(
            f"Contradiction found ({'resolved' if c.resolved else 'unresolved'}): {c.statement}"
        )

    if model.knowledge.unknown:
        lines.append(f"{len(model.knowledge.unknown)} open knowledge gap(s) remain.")

    if model.next_actions.questions:
        lines.append(f"{len(model.next_actions.questions)} open/blocking item(s) for what's next.")

    return "\n".join(lines)


def _render_prompt(facts: str) -> str:
    return render_prompt_template(
        _PROMPT_DIR / "report_executive_summary.md", facts, "", _MAX_CONTEXT_CHARS
    )


def _fallback_html(title: str, model: ReportViewModel) -> str:
    """A minimal, code-generated (never LLM-authored) HTML fallback for any
    consumer still reading `html_content` directly — never the primary
    rendering path (the frontend renders `view_model`). Deliberately
    plain: one paragraph plus the executive summary, no attempt to
    reproduce the old prose-report's sections.

    Leads with the user's own request, not `title` (an AI-generated label
    for the workflow that answered it) — same hierarchy the real renderer
    uses, so the fallback identifies a report the same way.

    Every interpolated value is escaped: `question` is verbatim user input
    and `summary` is LLM output, neither of which may be trusted to be
    markup-free just because the frontend happens to render this inside a
    `sandbox=""` iframe."""
    summary = escape(
        model.executive_summary or "No executive summary was generated for this report."
    )
    question = escape(model.header.question)
    escaped_title = escape(title)
    return (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f'<title>{escaped_title}</title></head><body style="font-family:sans-serif;'
        'max-width:720px;margin:40px auto;line-height:1.6;color:#1e293b">'
        f"<h1 style='font-size:20px'>{question}</h1>"
        f"<p style='color:#64748b;font-size:13px'>Investigated as {escaped_title}</p>"
        f"<p>{summary}</p>"
        "<p style='color:#94a3b8;font-size:11px'>This is a fallback rendering. "
        "See the Reports page for the full visual report.</p>"
        "</body></html>"
    )


class ReportGenerationAgent:
    """Implements IAgent for goal=generate_report.

    Stateless singleton, same pattern as every other agent — no db/graph
    session needed since this agent runs no tools of its own.
    """

    async def run(self, context: AgentContext) -> AgentOutput:
        subject_id: str = context.subject.subject_id
        workflow = context.extras.get("workflow")

        # This agent exists purely to synthesize a workflow's own stages —
        # dispatched only from approve_workflow (see api/v1/routers/
        # workflows.py). It has nothing to synthesize without one, so a
        # standalone run (POST /agent-runs with goal=generate_report and no
        # workflow context) fails loudly here rather than burning an LLM
        # call on an empty report — same guard style as create_branch_agent.
        if workflow is None:
            raise ReportGenerationExecutionError(
                "report_generation requires a workflow context — it is not a standalone goal."
            )

        bundles = dp.fetch_all_stage_bundles(workflow)
        completed_stages = [s for s in dp.STAGE_ORDER if bundles.get(s) is not None]

        logger.info(
            "report_generation_agent_started subject_id=%s completed_stages=%s model=%s",
            subject_id,
            ",".join(completed_stages) or "(none)",
            context.model,
        )

        evidence: list[Evidence] = [
            Evidence(
                kind="tool_call",
                reference="build_report_view_model",
                summary=(
                    f"Built a deterministic view model from {len(completed_stages)} completed "
                    f"stage(s): {', '.join(completed_stages) or '(none)'}. No LLM call was used "
                    "to decide report structure — see app.agents.report_generation.view_model."
                ),
            )
        ]

        # Deterministic — everything except `executive_summary` is decided
        # here, before any LLM call happens (ADR §13's architectural rule).
        model = build_report_view_model(workflow, bundles)

        title = (
            f"{workflow.title} — investigation report" if workflow.title else "Investigation report"
        )
        try:
            llm_metadata: dict[str, Any] = {}
            raw_response = await _call_llm(
                user_prompt=_render_prompt(_summary_prompt_facts(model)),
                model=context.model,
                stage=stage_for(context.extras, STAGE_GENERATION_STAGE),
                metadata_out=llm_metadata,
                context=context,
            )
            data = parse_json_response(raw_response, ReportGenerationLLMError)
            title = str(data.get("title") or title).strip() or title
            summary_text = str(data.get("executive_summary") or "").strip()
            model = dataclasses.replace(model, executive_summary=summary_text or None)
            evidence.append(
                Evidence(
                    kind="llm_reasoning",
                    reference="executive_summary",
                    summary=(
                        f"Narrated the already-built view model into a "
                        f"{len(summary_text)}-character executive summary — this call could not "
                        "add or remove a hypothesis, badge, or section; it only chose wording."
                    ),
                )
            )
        except ReportGenerationLLMError as exc:
            # A failed narration must never block the report — every other
            # section is already fully decided and renders correctly with
            # `executive_summary=None` (see ReportViewModel's own docstring).
            logger.warning(
                "report_generation_executive_summary_failed subject_id=%s error=%s",
                subject_id,
                str(exc),
            )
            evidence.append(
                Evidence(
                    kind="llm_reasoning",
                    reference="executive_summary",
                    summary=f"FAILED: executive summary generation failed ({exc}); "
                    "the rest of the report is unaffected.",
                )
            )

        view_model_json = to_json_dict(model)
        html = _fallback_html(title, model)

        # Confidence tracks completeness, not narrative quality — a report
        # built from every stage is strictly more trustworthy than one
        # built from a partial workflow (which shouldn't normally happen,
        # since this only ever dispatches after approval, but a workflow
        # can still be approved mid-sequence via future stage types).
        total_stages = len(dp.STAGE_ORDER)
        completeness = len(completed_stages) / total_stages if total_stages else 0.0
        confidence_score = 0.5 + 0.4 * completeness
        confidence_reasoning = (
            f"{len(completed_stages)} of {total_stages} workflow stages had a completed "
            "result available to build the view model from."
        )

        logger.info(
            "report_generation_agent_completed subject_id=%s title=%s confidence=%.2f "
            "hypotheses_state=%s hypotheses_count=%d",
            subject_id,
            title,
            confidence_score,
            model.hypotheses.synthesis_state.value,
            len(model.hypotheses.items),
        )

        return AgentOutput(
            agent_id="report_generation",
            subject_id=subject_id,
            confidence=Confidence(score=confidence_score, reasoning=confidence_reasoning),
            evidence=evidence,
            result={"title": title, "view_model": view_model_json, "html": html},
            prompt_version=_PROMPT_VERSION,
        )
