"""add oauth app credentials table

Revision ID: 4d24cbe6bf92
Revises: cfd317dedf65
Create Date: 2026-07-31 10:28:40.789811

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d24cbe6bf92"
down_revision: str | None = "cfd317dedf65"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_app_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_key", sa.String(length=32), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=False),
        sa.Column("encrypted_client_secret", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_key"),
    )
    # NOTE: autogenerate also proposed dropping 'knowledge_connections' here -
    # unrelated pre-existing drift (that model isn't imported in this file,
    # so autogenerate can't see it - see the model-import list above). Left
    # untouched; that table is still actively used by
    # app.api.v1.routers.knowledge / app.knowledge.registry.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("oauth_app_credentials")
    # ### end Alembic commands ###
