import { useRef, useState } from "react";
import { LayoutDashboard, AlignLeft, FlaskConical, Code } from "lucide-react";
import { EvidencePanel } from "../EvidencePanel";
import { ExecutionLogPanel } from "../workflow/ExecutionLogPanel";
import {
  DevelopmentResultDetails,
  PlanningResultDetails,
  TestingResultDetails,
} from "../agents/StageResultDetails";
import { BlueprintExplorer } from "../blueprint/BlueprintExplorer";
import type { AgentStep, DevelopmentPlanResult, PlanningResult, TestPlanResult } from "../../types/agent";
import type { BlueprintArtifact } from "../../types/blueprint";

/**
 * Tabbed result view (Visual Blueprint | Summary | Evidence | Log | JSON)
 * for one agent step. Reads exclusively from persisted step.result — the
 * blueprint (when present) was already generated by the agent itself and
 * stored in the step's result JSON at run time; this component never
 * recomputes or re-generates anything.
 *
 * Shared between WorkflowPage (a workflow's stage results) and
 * RunDetailPage (any standalone or workflow-stage run's detail page) —
 * originally lived only inside WorkflowPage, which meant every run viewed
 * via /runs/{runId} (i.e. every run reached from Run History) fell back to
 * a raw JSON dump instead of rendering its blueprint. Moving it here once
 * fixes that for every run, standalone or not, without a second
 * implementation.
 */

type ResultTab = "blueprint" | "summary" | "evidence" | "log" | "json";

const TAB_CONFIG: {
  id: ResultTab;
  label: string;
  icon: typeof LayoutDashboard;
  always?: boolean;
}[] = [
  { id: "blueprint", label: "Visual Blueprint", icon: LayoutDashboard },
  { id: "summary", label: "Summary", icon: AlignLeft },
  { id: "evidence", label: "Evidence", icon: FlaskConical },
  { id: "log", label: "Log", icon: Code },
  { id: "json", label: "JSON", icon: Code, always: true },
];

export function StageResultPanel({
  stage,
  step,
  agentLabel,
  evidence,
}: {
  stage: string | null;
  step: AgentStep;
  agentLabel: string;
  evidence: AgentStep["evidence"];
}) {
  const planningResult = stage === "planning" ? (step.result as unknown as PlanningResult) : null;
  const developmentResult = stage === "development" ? (step.result as unknown as DevelopmentPlanResult) : null;

  const blueprint =
    (planningResult?.blueprint ?? developmentResult?.blueprint) as BlueprintArtifact | null | undefined;

  // The real counts, not a diagram-node-count approximation — see the
  // matching comment on BlueprintExplorerProps for why these must win.
  const implementationStepsCount =
    planningResult?.implementation_steps?.length ?? developmentResult?.implementation_phases?.length;
  const affectedComponentsCount =
    planningResult?.affected_components?.length ?? developmentResult?.components?.length;
  const risksCount = planningResult?.risk_considerations?.length ?? developmentResult?.risks?.length;

  const hasBlueprint = Boolean(blueprint && blueprint.diagrams.length > 0);
  const hasSummary = stage === "planning" || stage === "development" || stage === "testing";

  const defaultTab: ResultTab = hasBlueprint ? "blueprint" : hasSummary ? "summary" : "evidence";
  const [activeTab, setActiveTab] = useState<ResultTab>(defaultTab);

  // Reset to best default when the stage changes
  const stageRef = useRef(stage);
  if (stageRef.current !== stage) {
    stageRef.current = stage;
    setActiveTab(hasBlueprint ? "blueprint" : hasSummary ? "summary" : "evidence");
  }

  const visibleTabs = TAB_CONFIG.filter((t) => {
    if (t.id === "blueprint") return hasBlueprint;
    if (t.id === "summary") return hasSummary;
    return true;
  });

  const panelId = (id: ResultTab) => `stage-result-panel-${id}`;
  const tabId = (id: ResultTab) => `stage-result-tab-${id}`;

  function focusTab(id: ResultTab) {
    document.getElementById(tabId(id))?.focus();
  }

  function handleTabKeyDown(event: React.KeyboardEvent<HTMLButtonElement>, index: number) {
    // Standard ARIA tabs arrow-key navigation — Left/Right (and Home/End)
    // move focus between tabs and activate the newly-focused one,
    // matching the pattern screen readers expect from role="tab".
    if (event.key === "ArrowRight" || event.key === "ArrowLeft") {
      event.preventDefault();
      const delta = event.key === "ArrowRight" ? 1 : -1;
      const next = visibleTabs[(index + delta + visibleTabs.length) % visibleTabs.length];
      setActiveTab(next.id);
      focusTab(next.id);
    } else if (event.key === "Home") {
      event.preventDefault();
      setActiveTab(visibleTabs[0].id);
      focusTab(visibleTabs[0].id);
    } else if (event.key === "End") {
      event.preventDefault();
      const last = visibleTabs[visibleTabs.length - 1];
      setActiveTab(last.id);
      focusTab(last.id);
    }
  }

  return (
    <div className="flex flex-col overflow-hidden rounded-xl border border-slate-800 bg-slate-900/60">
      {/* Tab bar */}
      <div
        className="flex items-center gap-0.5 border-b border-slate-800 px-2 pt-2"
        role="tablist"
        aria-label="Stage result views"
      >
        {visibleTabs.map((tab, index) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              id={tabId(tab.id)}
              type="button"
              onClick={() => setActiveTab(tab.id)}
              onKeyDown={(e) => handleTabKeyDown(e, index)}
              className={`flex items-center gap-1.5 rounded-t px-3 py-2 text-xs font-medium transition-colors ${
                isActive
                  ? "border-b-2 border-brand-500 text-brand-300"
                  : "text-slate-500 hover:text-slate-300"
              }`}
              aria-selected={isActive}
              aria-controls={panelId(tab.id)}
              role="tab"
              tabIndex={isActive ? 0 : -1}
            >
              <Icon className="h-3 w-3" aria-hidden="true" />
              {tab.label}
              {tab.id === "blueprint" && hasBlueprint && (
                <span className="rounded-full bg-brand-500/20 px-1.5 py-0.5 text-[9px] font-semibold text-brand-300">
                  NEW
                </span>
              )}
            </button>
          );
        })}
      </div>

      {/* Tab panels */}
      <div className="min-h-[300px] p-4">
        {activeTab === "blueprint" && blueprint && (
          <div id={panelId("blueprint")} role="tabpanel" aria-labelledby={tabId("blueprint")} tabIndex={0}>
            <BlueprintExplorer
              blueprint={blueprint}
              implementationStepsCount={implementationStepsCount}
              affectedComponentsCount={affectedComponentsCount}
              risksCount={risksCount}
            />
          </div>
        )}

        {activeTab === "summary" && (
          <div
            id={panelId("summary")}
            role="tabpanel"
            aria-labelledby={tabId("summary")}
            tabIndex={0}
            className="flex flex-col gap-4"
          >
            {stage === "planning" && (
              <PlanningResultDetails result={step.result as unknown as PlanningResult} />
            )}
            {stage === "development" && (
              <DevelopmentResultDetails result={step.result as unknown as DevelopmentPlanResult} />
            )}
            {stage === "testing" && (
              <TestingResultDetails result={step.result as unknown as TestPlanResult} />
            )}
          </div>
        )}

        {activeTab === "evidence" && (
          <div id={panelId("evidence")} role="tabpanel" aria-labelledby={tabId("evidence")} tabIndex={0}>
            <EvidencePanel evidence={evidence} />
          </div>
        )}

        {activeTab === "log" && (
          <div id={panelId("log")} role="tabpanel" aria-labelledby={tabId("log")} tabIndex={0}>
            <ExecutionLogPanel step={step} agentLabel={agentLabel} llmTrace={planningResult?.llm_trace} />
          </div>
        )}

        {activeTab === "json" && (
          <div id={panelId("json")} role="tabpanel" aria-labelledby={tabId("json")} tabIndex={0}>
            <pre className="max-h-96 overflow-auto rounded-lg bg-slate-950 p-3 font-mono text-xs text-slate-300">
              {JSON.stringify(step.result, null, 2)}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}
